version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=strikes_db
      - POSTGRES_PASSWORD=strikes_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local